### ISSUE TITLE
Python venv are not displayed in command line

### ISSUE THREAD

**Issue by jo460464** [Kleinjohann/dotfiles#1]
When activating a conda env the active env is displayed in the command line like in the example below.
![Screenshot from 2023-07-15 16-53-05](https://github.com/Kleinjohann/dotfiles/assets/48690324/07a641a1-5145-47ad-b12d-0047502aa13f)
When activating a python venv this does not happen although venv is active. 
![Screenshot from 2023-07-15 16-57-36](https://github.com/Kleinjohann/dotfiles/assets/48690324/e2d0c109-c97b-4a35-9cda-fd11cf4f7ad7)

**Comment by Kleinjohann** [comment]
Fixed since 7539752 by switching to zsh with p10k.
